version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres-container
    restart: always
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      TZ: 'America/Sao_Paulo'
    volumes:
      - postgres-data:/postgres
    networks:
      - containers-network

volumes:
  postgres-data:

networks:
  containers-network:
    driver: bridge
