
version: '3.8'

services:
  postgresql:
    image: postgresql:14.2-alpine
    container_name: postgresql-container
    restart: always
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      TZ: 'America/Sao_Paulo'
    volumes:
      - postgresql-data:/postgresql
    networks:
      - containers-network

  redis:
    image: redis:6.2.6-alpine
    container_name: redis-container
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/redis/data
    networks:
      - containers-network

volumes:
  postgresql-data:
  redis-data:

networks:
  containers-network:
    driver: bridge
