version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres-container
    restart: always
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      TZ: 'America/Sao_Paulo'
    networks:
      - containers-network

  mongo:
    container_name: mongo-container
    image: mongo:4.2.20
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - containers-network

  api:
    build: .
    container_name: api-container
    command: 'yarn start'
    restart: always
    ports:
      - ${API_PORT}:8080
    depends_on:
      - postgres
      - mongo
    networks:
      - containers-network

  tests:
    build: .
    container_name: tests-container
    command: 'yarn test:ci'

networks:
  containers-network:
    driver: bridge
