name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: yarn
    - name: Build
      run: yarn build

  lint:
    needs: [build]

    runs-on: ubuntu-20.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: yarn
    - name: Lint
      run: yarn lint

  tests:
    needs: [build]

    runs-on: ubuntu-20.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: yarn
    - name: Tests
      run: yarn test

  tests-mutation:
    needs: [build, lint, tests]

    runs-on: ubuntu-20.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v2
    - name: Installation of Node.js dependencies
      run: yarn
    - name: Mutation tests
      run: yarn test:mutation
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        BRANCH: ${{ env.GITHUB_REF_SLUG }}


  # deploy:
  #   needs: [build, lint, tests, tests-mutation]

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - name: Project checkout
  #     uses: actions/checkout@v2
  #   - name: Deploy app on Heroku (https://management-tools.herokuapp.com/docs-api/)
  #     uses: akhileshns/heroku-deploy@v3.12.12
  #     with:
  #       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #       heroku_app_name: "management-tools"
  #       heroku_email: ${{secrets.HEROKU_EMAIL}}
